### ISSUE TITLE
Can't download via 'download.gluster.org' repository

### ISSUE THREAD

**Issue by johalaoui** [gluster/project-infrastructure#168]
Hello,

This issue is related to this https://github.com/gluster/glusterfs/issues/3640.
Apparently it is still not fixed. Is there any status update?
Thanks in advance.

```
    deb11GlusterRepackagedBox: deb https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye main
    deb11GlusterRepackagedBox: Hit:1 http://deb.debian.org/debian bullseye InRelease
    deb11GlusterRepackagedBox: Hit:2 http://security.debian.org/debian-security bullseye-security InRelease
    deb11GlusterRepackagedBox: Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
    deb11GlusterRepackagedBox: Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
    deb11GlusterRepackagedBox: Hit:5 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye InRelease
    deb11GlusterRepackagedBox: Reading package lists...
    deb11GlusterRepackagedBox: Reading package lists...
    deb11GlusterRepackagedBox: Building dependency tree...
    deb11GlusterRepackagedBox: 
    deb11GlusterRepackagedBox: Reading state information...
    deb11GlusterRepackagedBox: The following additional packages will be installed:
    deb11GlusterRepackagedBox:   attr fuse3 glusterfs-client glusterfs-common keyutils libevent-2.1-7
    deb11GlusterRepackagedBox:   libfuse3-3 libgfapi0 libgfchangelog0 libgfrpc0 libgfxdr0 libglusterd0
    deb11GlusterRepackagedBox:   libglusterfs0 libgoogle-perftools4 libinih1 libnfsidmap2
    deb11GlusterRepackagedBox:   libtcmalloc-minimal4 libunwind8 liburcu6 nfs-common psmisc
    deb11GlusterRepackagedBox:   python3-cffi-backend python3-cryptography python3-jwt python3-prettytable
    deb11GlusterRepackagedBox:   rpcbind xfsprogs
    deb11GlusterRepackagedBox: Suggested packages:
    deb11GlusterRepackagedBox:   open-iscsi watchdog python-cryptography-doc python3-cryptography-vectors
    deb11GlusterRepackagedBox:   python3-crypto xfsdump acl quota
    deb11GlusterRepackagedBox: The following NEW packages will be installed:
    deb11GlusterRepackagedBox:   attr fuse3 glusterfs-client glusterfs-common glusterfs-server keyutils
    deb11GlusterRepackagedBox:   libevent-2.1-7 libfuse3-3 libgfapi0 libgfchangelog0 libgfrpc0 libgfxdr0
    deb11GlusterRepackagedBox:   libglusterd0 libglusterfs0 libgoogle-perftools4 libinih1 libnfsidmap2
    deb11GlusterRepackagedBox:   libtcmalloc-minimal4 libunwind8 liburcu6 nfs-common psmisc
    deb11GlusterRepackagedBox:   python3-cffi-backend python3-cryptography python3-jwt python3-prettytable
    deb11GlusterRepackagedBox:   rpcbind xfsprogs
    deb11GlusterRepackagedBox: 0 upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
    deb11GlusterRepackagedBox: Need to get 31.0 MB/33.7 MB of archives.
    deb11GlusterRepackagedBox: After this operation, 54.4 MB of additional disk space will be used.
    deb11GlusterRepackagedBox: Get:1 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfxdr0 amd64 10.2-1 [3109 kB]
    deb11GlusterRepackagedBox: Err:1 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfxdr0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:2 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libglusterfs0 amd64 10.2-1 [3352 kB]
    deb11GlusterRepackagedBox: Err:2 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libglusterfs0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:3 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfrpc0 amd64 10.2-1 [3134 kB]
    deb11GlusterRepackagedBox: Err:3 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfrpc0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:4 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfapi0 amd64 10.2-1 [3161 kB]
    deb11GlusterRepackagedBox: Err:4 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfapi0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:5 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfchangelog0 amd64 10.2-1 [3116 kB]
    deb11GlusterRepackagedBox: Err:5 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libgfchangelog0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:6 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libglusterd0 amd64 10.2-1 [3096 kB]
    deb11GlusterRepackagedBox: Err:6 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 libglusterd0 amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:7 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-common amd64 10.2-1 [5626 kB]
    deb11GlusterRepackagedBox: Err:7 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-common amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:8 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-client amd64 10.2-1 [3116 kB]
    deb11GlusterRepackagedBox: Err:8 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-client amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: Get:9 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-server amd64 10.2-1 [3285 kB]
    deb11GlusterRepackagedBox: Err:9 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt bullseye/main amd64 glusterfs-server amd64 10.2-1
    deb11GlusterRepackagedBox:   Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libgfxdr0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libglusterfs0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: 
    deb11GlusterRepackagedBox: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libgfrpc0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libgfapi0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libgfchangelog0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/libglusterd0_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/glusterfs-common_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/glusterfs-client_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Failed to fetch https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/11/amd64/apt/pool/main/g/glusterfs/glusterfs-server_10.2-1_amd64.deb  Error reading from server - read (5: Input/output error) [IP: 8.43.85.185 443]
    deb11GlusterRepackagedBox: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
